# Generated by Django 3.2.5 on 2022-06-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220611_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editors_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='top_headlines',
            field=models.BooleanField(default=False),
        ),
    ]
