# Generated by Django 3.2.5 on 2022-06-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220611_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
