# Generated by Django 3.2.5 on 2022-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='weekly_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
